fileserver:
    dev:
#        path: D:\anbiao3.0\FileManagement\webapps\FileManager\static\
#        url: http://202.100.168.150:8203/FileManager/static/
        path: D:\BS\static\
        url: http://60.171.241.126:8204/
        flag: false
        ##
gpsserver:
    dev:
        pointurl: http://60.171.241.126:7096/
        imgurl: http://60.171.241.126:7096/
alarmserver:
    dev:
        address: 河南
