#服务器端口
server:
  port: 9101

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://202.100.168.150:3453/blade-auth?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: mxcx123
